package main

import (
	"github.com/iancoleman/strcase"
	"google.golang.org/protobuf/compiler/protogen"
)

const variant = ".tr"

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + variant + ".pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by service-helper. DO NOT EDIT.")
	g.P("// source: ", file.GeneratedFilenamePrefix)

	g.P("package ", file.GoPackageName)
	g.P()

	g.P("import _ \"embed\"")

	g.P("//go:embed " + file.Desc.Name() + ".swagger.json")

	varName := strcase.ToLowerCamel(string(file.GoPackageName) + "SwaggerJSON")
	g.P("var " + varName + "[] byte")
}
