package main

import (
	"fmt"
	"path"
	"strings"

	"github.com/iancoleman/strcase"
	"google.golang.org/protobuf/compiler/protogen"
)

const variant = ".tr"

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filepath := file.GeneratedFilenamePrefix + fmt.Sprintf(".pb%s.go", variant)
	g := gen.NewGeneratedFile(filepath, file.GoImportPath)

	g.P("// Code generated by servitor. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()

	g.P("package ", file.GoPackageName)
	g.P()

	g.P("import _ \"embed\"")

	filename := strings.TrimSuffix(path.Base(file.GeneratedFilenamePrefix), ".proto")
	g.P("//go:embed " + filename + ".swagger.json")
	varName := strcase.ToLowerCamel(string(file.Desc.Name())+"Swagger") + "JSON"
	g.P("var " + varName + "[] byte")
	g.P()

	g.P("func SwaggerDef() []byte {")
	g.P("return " + varName)
	g.P("}")
}
